version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: DockerFile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - "9000"
    ports:
      - "9000:9000"
    command: npm run dev
